; =========================================
; ENVIRONNEMENT 1 : LE CERVEAU (ESP32-S3)
; =========================================
[env:lumi_brain_s3]
platform = espressif32@6.7.0 
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Port COM à adapter selon la carte branchée
upload_port = COM12
upload_speed = 115200

; --- PARTITIONS ET MÉMOIRE S3 ---
board_build.partitions = huge_app.csv 
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.flash_mode = dio
board_build.arduino.memory_type = dio_opi

build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 
    -D WAKE_WORD=\"Lumi\"

; --- BIBLIOTHÈQUES S3 ---
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    bblanchon/ArduinoJson
    tzapu/WiFiManager
    https://github.com/schreibfaul1/ESP32-audioI2S/archive/refs/tags/2.0.6.zip

; --- SÉPARATION DU CODE ---
; Compile tout ce qui est dans src/brain, ignore la caméra
build_src_filter = +<brain/> -<vision/> 


; =========================================
; ENVIRONNEMENT 2 : LA VISION (ESP32-CAM)
; =========================================
[env:lumi_vision_cam]
; La plateforme la plus stable pour l'ESP32-CAM standard
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

; Port COM à adapter selon ton adaptateur FTDI
; upload_port = COM13
upload_speed = 115200

; L'ESP32-CAM possède généralement 4Mo de flash et 4Mo de PSRAM
board_build.partitions = min_spiffs.csv

build_flags =
    -D BOARD_HAS_PSRAM
    -D CORE_DEBUG_LEVEL=3
    -D CAMERA_MODEL_AI_THINKER

; --- BIBLIOTHÈQUES CAMÉRA ---
; L'ESP32-CAM n'a pas besoin de la bibliothèque audio ni des capteurs.
; La bibliothèque officielle fournit le fichier esp_camera.h.
lib_deps =
    https://github.com/espressif/esp32-camera.git
    bblanchon/ArduinoJson

; --- SÉPARATION DU CODE ---
; Compile tout ce qui est dans src/vision, ignore le cerveau
build_src_filter = +<vision/> -<brain/>

; Commandes utiles depuis le dossier du projet :
;   pio run -e lumi_brain_s3 -t upload    ; compiler et flasher le cerveau
;   pio run -e lumi_vision_cam -t upload  ; compiler et flasher la caméra
;   pio device monitor -e lumi_brain_s3   ; moniteur série du cerveau
;   pio device monitor -e lumi_vision_cam ; moniteur série de la caméra